gui:
  language: 'en' # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl' | 'ja'
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - '#555555'
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse # set to `default` to have no background colour
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  showIcons: true
  showBottomLine: false
os:
  editCommand: 'nvim-qt'
